site_name: Oddworks SDK for Android
site_url: http://android.guide.oddnetworks.com
site_description: Odd Networks Android Developer Guide
repo_url: https://github.com/oddnetworks/oddworks-android-sdk
site_favicon: assets/favicon.ico
site_author: Erik Straub
copyright: Odd Networks
google_analytics: ["UA-68853545-3", "android.guide.oddnetworks.com"]
extra_css: []
pages:
- Welcome:
    - Introduction: index.md
    - Overview: overview.md
- "Getting Started":
    - Setup: setup.md
    - Requests: requests.md
    - Authentication: authentication.md
    - Analytics: analytics.md
theme: readthedocs
